### ISSUE TITLE
SBANavigationQuestionStep crash: [__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by wbmd-sagarwal** [Sage-Bionetworks/ResearchUXFactory-iOS#7]
We are experiencing the crash while using class SBANavigationQuestionStep. 
- This crash occured while taking the survey with identifier "Twins-prenatal-visit" for the study identifier "stsi-preganancy"
- Error found in line: 76 in function: SBANavigationQuestionStep:
Please let us know if you need any other information from our end.
Stack trace - 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString timeIntervalSinceReferenceDate]: unrecognized selector sent to instance 0x618000437d40'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f698d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010eb5421e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f708f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010f61e005 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010f61db88 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x000000010f654648 -[NSDate compare:] + 56
	6   Foundation                          0x000000010ac60d11 -[NSComparisonPredicateOperator performPrimitiveOperationUsingObject:andObject:] + 369
	7   Foundation                          0x000000010abd0ba6 -[NSPredicateOperator performOperationUsingObject:andObject:] + 284
	8   Foundation                          0x000000010abd0954 -[NSComparisonPredicate evaluateWithObject:substitutionVariables:] + 313
	9   ResearchUXFactory                   0x0000000109904ca8 _TFC17ResearchUXFactory25SBANavigationQuestionStep18nextStepIdentifierfT4withCSo13ORKTaskResult3andGSqGSaS1____GSqSS_ + 1320
	10  ResearchUXFactory                   0x0000000109906a91 _TTWC17ResearchUXFactory25SBANavigationQuestionStepS_17SBANavigationRuleS_FS1_18nextStepIdentifierfT4withCSo13ORKTaskResult3andGSqGSaS2____GSqSS_ + 97
	11  ResearchUXFactory                   0x00000001098822fd _TFC17ResearchUXFactory23SBANavigableOrderedTaskP33_8F732068F5F38D0EB9AEB60B85F69EEB9superStepfT5afterGSqCSo7ORKStep_4withCSo13ORKTaskResult_GSqS1__ + 829
	12  ResearchUXFactory                   0x00000001098831e2 _TFC17ResearchUXFactory23SBANavigableOrderedTask4stepfT5afterGSqCSo7ORKStep_4withCSo13ORKTaskResult_GSqS1__ + 786
	13  ResearchUXFactory                   0x0000000109883d9f _TToFC17ResearchUXFactory23SBANavigableOrderedTask4stepfT5afterGSqCSo7ORKStep_4withCSo13ORKTaskResult_GSqS1__ + 79
	14  BridgeAppSDK                        0x000000010e91eb58 _TFC12BridgeAppSDK13SBASurveyTask4stepfT5afterGSqCSo7ORKStep_4withCSo13ORKTaskResult_GSqS1__ + 664
	15  BridgeAppSDK                        0x000000010e91ecbf _TToFC12BridgeAppSDK13SBASurveyTask4stepfT5afterGSqCSo7ORKStep_4withCSo13ORKTaskResult_GSqS1__ + 79
	16  ResearchKit                         0x000000010ddf4e3d -[ORKTaskViewController stepAfterStep:] + 141
	17  ResearchKit                         0x000000010ddf4b68 -[ORKTaskViewController stepViewControllerHasNextStep:] + 120
	18  ResearchKit                         0x000000010ddbd10a -[ORKStepViewController hasNextStep] + 122
	19  ResearchKit                         0x000000010df563dc -[ORKQuestionStepViewController notifyDelegateOnResultChange] + 76
	20  ResearchKit                         0x000000010df5629d -[ORKQuestionStepViewController saveAnswer:] + 189
	21  ResearchKit                         0x000000010df58e05 -[ORKQuestionStepViewController answerCell:answerDidChangeTo:dueUserAction:] + 101
	22  ResearchKit                         0x000000010de951ef -[ORKSurveyAnswerCellForPicker ork_setAnswer:] + 159
	23  ResearchKit                         0x000000010de95139 -[ORKSurveyAnswerCellForPicker valueChangedDueUserAction:] + 121
	24  ResearchKit                         0x000000010de95268 -[ORKSurveyAnswerCellForPicker picker:answerDidChangeTo:] + 88
	25  ResearchKit                         0x000000010de626e7 -[ORKDateTimePicker valueDidChange:] + 503
	26  ResearchKit                         0x000000010de624e9 -[ORKDateTimePicker pickerWillAppear] + 89
	27  ResearchKit                         0x000000010de9496f -[ORKSurveyAnswerCellForPicker loadPicker] + 287
	28  ResearchKit                         0x000000010df54e9d -[ORKQuestionStepViewController viewDidAppear:] + 237
	29  UIKit                               0x000000010b295a6c -[UIViewController _setViewAppearState:isAnimating:] + 945
	30  UIKit                               0x000000010b296388 -[UIViewController _endAppearanceTransition:] + 197
	31  UIKit                               0x000000010b9166d0 -[UIPageViewController _childEndAppearanceTransition:] + 58
	32  UIKit                               0x000000010b9167db -[UIPageViewController _child:endAppearanceTransitionIfPossible:] + 134
	33  UIKit                               0x000000010b92113a -[UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:] + 425
	34  UIKit                               0x000000010ba1dc60 -[_UIQueuingScrollView _notifyDelegateDidEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:] + 143
	35  UIKit                               0x000000010ba1d9c3 __78-[_UIQueuingScrollView _enqueueAnimatedScrollInDirection:withView:completion:]_block_invoke.299 + 69
	36  UIKit                               0x000000010ba18f9b -[_UITransitionState cleanupWithFinishedState:completedState:] + 35
	37  UIKit                               0x000000010ba1c39b -[_UIQueuingScrollView _cleanUpCompletionState:didFinish:didComplete:] + 96
	38  UIKit                               0x000000010ba1ee9b -[_UIQueuingScrollView _didScrollWithAnimation:force:] + 685
	39  UIKit                               0x000000010ba1a49e -[_UIQueuingScrollView _scrollViewAnimationEnded:finished:] + 93
	40  UIKit                               0x000000010b2797a3 -[UIAnimator stopAnimation:] + 429
	41  UIKit                               0x000000010b279f6c -[UIAnimator(Static) _advanceAnimationsOfType:withTimestamp:] + 288
	42  QuartzCore                          0x0000000109d1a895 _ZN2CA7Display15DisplayLinkItem8dispatchEy + 57
	43  QuartzCore                          0x0000000109d1a755 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 449
	44  CoreFoundation                      0x000000010f62adb4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	45  CoreFoundation                      0x000000010f62aa43 __CFRunLoopDoTimer + 1075
	46  CoreFoundation                      0x000000010f62a5ca __CFRunLoopDoTimers + 250
	47  CoreFoundation                      0x000000010f6222f1 __CFRunLoopRun + 2065
	48  CoreFoundation                      0x000000010f621884 CFRunLoopRunSpecific + 420
	49  GraphicsServices                    0x0000000111f8ea6f GSEventRunModal + 161
	50  UIKit                               0x000000010b0edc68 UIApplicationMain + 159
	51  PregnancyApp                        0x0000000106655f4e main + 62
	52  libdyld.dylib                       0x000000011505d68d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by wbmd-sagarwal** [comment]
@wbmd-pbeyer @wbmd-omokretsov

**Comment by wbmd-pbeyer** [comment]
WebMD tracking:  https://jira.webmd.net/browse/PPE-97124

**Comment by syoung-smallwisdom** [comment]
https://github.com/Sage-Bionetworks/BridgeAppSDK/pull/170

**Comment by syoung-smallwisdom** [comment]
Merged https://github.com/Sage-Bionetworks/BridgeAppSDK/commit/761d5731f4c180cd0fa48a102dcd0600ee554153

**Comment by syoung-smallwisdom** [comment]
@wbmd-pbeyer Apparently there is an issue with the Web Researcher UI where dates are sent as strings. I've put in code converting them from ISO8601 or standard US-english format of "MM/dd/yyyy" (which is what you guys used for the date).
